apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec: 
      containers:
      - name: hello-world-container
        image: hello-world:v1
        ports:
        - containerPort: 8080
